Main
bfayers/pyEOCharging pull request #2
Opened 2022-11-18 22:41 UTC by MuddyRock

Add ability to get/set charger options.
For example, setting off peak mode, solar mode and scheduled mode all to off (0), while the charger is enabled will effectively turn  the charger on and send power to the car.

For full available options, see the class definition, and the reply from get_chargeOpts()

2022-11-19 12:46 UTC, bfayers commented
Hi! thanks for the PR, just a comment or two that I'll add to individual lines

2022-11-19 12:48 UTC, bfayers requested changes

2022-11-19 12:48 UTC, bfayers commented on README.md
> +Forked by MuddyRock from @bfayers original work.
Remove statement that it's a fork for this to be merged

2022-11-23 10:21 UTC, bfayers approved these changes
Thanks. I'll get around to testing the new features later on and hopefully merge this.

2022-12-14 20:34 UTC, MuddyRock commented
Hi
Sorry - I'm a bit new to GitHub and still figuring it out (including sending messages up till now). I can see that you've approved my pull request but that the changes haven't made it into your version.
It's probably something I've done - for a start, I've now accidentally closed the PR twice!
For info: I've also worked out how to connect to the Smart Hub wifi directly. It has some open ports that might be valid targets for a man-in-the-middle intercept when the app talks to it (although the only thing I can see that the app does which require direct connect is connecting to a new WiFi network, it wouldn't surprise me if more functionality was available through this route).
Cheers
MuddyRock

2022-12-15 08:33 UTC, bfayers commented
Nah, it's my fault -- I hadn't had a chance to test all the new features yet, but approved the changes to the code. hopefully i'll have some time over the weekend to test it.

As for the wifi network of the charger's themselves and their ports -- I've done *a lot* of digging on that already and found there is a way to put them in OCPP mode despite their claims that it doesn't support it. I've tried once to make that work but didn't really get anywhere (though, I think that was my fault) At some point I may try again to get it working on OCPP mode (that mode does completely disable functionality of the official app, though)

2022-12-16 18:29 UTC, MuddyRock commented
No worries and no rush - it's practically Christmas after all! 
If you get five minutes at some point, I'd appreciate some info on what you can do when connected to the charger's own WiFi network (and how to do it once connected).
I have successfully MITM'd the app when it's talking via the cloud, but I can't intercept calls on the local WiFI.
In an ideal world, I'd get full local control of the charger without it going out to the cloud, but I have a feeling that's being wildly optimistic!

2023-02-01 09:40 UTC, bfayers commented
Sorry for the long delay, got busy with stuff. All tested now and looks good to me!

2023-02-01 09:40 UTC, merged

2023-08-05 18:25 UTC, MuddyRock commented
Hi 
Did you ever get anywhere with the OCPP mode?

2023-08-05 20:47 UTC, bfayers commented
> Hi Did you ever get anywhere with the OCPP mode?

Haven't properly given it a try and frankly since the charger works at the moment I'd rather not mess with it too much haha